#!/bin/bash -l
#PBS -l nodes=1:ppn=5
#PBS -l walltime=00:10:00
#PBS -l mem=64gb
#PBS -e logs/
#PBS -o logs/
#PBS -m abe

cd $PBS_O_WORKDIR
module load Seurat/5.1.0-foss-2023a-R-4.3.2

#### CHANGE VALUES HERE ####
PATH_TO_SINGLECELL_SEURAT_OBJECT="tutorial/full_data/WMB-10Xv3_subset.rds"
PATH_TO_VISIUMHD="tutorial/full_data/Visium_HD_MouseBrain_008um.rds"
ANNOTATION_COLUMN_IN_SINGLECELL_OBJECT="class"
############################

Rscript runRCTD.R \
        --sc_input $PATH_TO_SINGLECELL_SEURAT_OBJECT \
        --sp_input $PATH_TO_VISIUMHD \
        --annot $ANNOTATION_COLUMN_IN_SINGLECELL_OBJECT
