#!/bin/bash -l
#PBS -l nodes=1:ppn=6
#PBS -l walltime=60:00:00
#PBS -l mem=100gb
#PBS -e logs/
#PBS -o logs/

cd $PBS_O_WORKDIR
nextflow run $VSC_DATA_VO_USER/spotless-benchmark/main.nf -profile hpc \
-c $VSC_DATA_VO_USER/visium-hd/visium_hd_brain_ff/2_run_rctd.config -ansi-log false \
--container_name csangara/sp_rctd:2.2.1-hd-seurat5.1.0
# --container_name csangara/sp_rctd:latest
# --container_name csangara/sp_rctd:2.2.1-seurat5.1.0
